version: "3.3"

services:

  api:
    build:
      context: .
    image: moleculer-demo
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 4000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal
      - tautoken-network

  qr:
    build:
      context: .
    image: moleculer-demo
    env_file: docker-compose.env
    environment:
      SERVICES: qr
    depends_on:
      - nats
    networks:
      - internal
      - tautoken-network


  wallet:
    build:
      context: .
    image: moleculer-demo
    env_file: docker-compose.env
    environment:
      SERVICES: wallet
    depends_on:
      - nats
    networks:
      - internal
      - tautoken-network

  nats:
    image: nats:2
    networks:
      - internal
      - tautoken-network

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
      - tautoken-network


networks:
  internal:
  tautoken-network:
    external:
      name: tautoken-network

volumes:
  data:
